### PR TITLE
Update UA-String

### PR DESCRIPTION
**Pull request by vinaybedre**
Updated user agent string with latest Chrome V73

### CODE REVIEW

**Comment by kevva** [comment]
Isn't it better to use the stable version? Guess it doesn't matter too much, just a thought :).

**Comment by vinaybedre** [comment]
As per https://itunes.apple.com/us/app/macos-mojave/id1398502828?ls=1&mt=12 updated Mac OS X version to 10.14.2
As per https://chromereleases.googleblog.com/2019/01/stable-channel-update-for-chrome-os.html updated Chrome version to 71.0.3578.127

**Comment by kevva** [comment]
Thanks @vinaybedre!

**Comment by vinaybedre** [comment]
@vinaybedre Can you publish a new version for npm?

**Comment by kevva** [comment]
I don't have publish rights.

**Comment by sindresorhus** [comment]
Published: https://github.com/sindresorhus/ua-string/releases/tag/v2.1.0

**Pull request merged**
